# Maybe Finance (https://github.com/maybe-finance/maybe) playbook
---
- name: Setup Maybe Finance
  hosts: maybe
  become: yes

  tasks:
    - name: Update system
      apt:
        update_cache: yes
        upgrade: dist
    - name: Install rbenv deps
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - libssl-dev
        - libreadline-dev
        - zlib1g-dev
        - build-essential
    - name: Install rbenv
      shell: |
        git clone https://github.com/rbenv/rbenv.git ~/.rbenv
        echo 'eval "$(~/.rbenv/bin/rbenv init - bash)"' >> ~/.bashrc
        git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
    - name: Install ruby
      shell: |
        ~/.rbenv/bin/rbenv install 3.3.0
        ~/.rbenv/bin/rbenv global 3.3.0
    - name: Install postgres
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql
        - postgresql-client
    - name: Create postgres user
      postgresql_user:
        db: postgres
        name: maybe
        password: maybe
        priv: "*.*:ALL"
    - name: Create postgres database
      postgresql_db:
        name: maybe
        owner: maybe
    - name: Clone Maybe Finance
      shell: | 
        git clone https://github.com/maybe-finance/maybe ~/maybe
    - name: Setup Maybe
      shell: |
        cd ~/maybe
        cp .env.example .env
        gem install bundler
        bundle install
        rails db:setup