---
- name: Update all packages on Debian, Ubuntu, Arch, CentOS, or Rocky Linux
  hosts: all
  become: yes

  tasks:
    - name: Update Package Cache (deb)
      command: "apt update"
      when: ansible_distribution in ['Ubuntu', 'Debian']
    - name: Upgrade Packages (deb)
      command: "apt upgrade -y"
      when: ansible_distribution in ['Ubuntu', 'Debian']
    - name: Update Packages (arch)
      command: "pacman -Syu --noconfirm"
      when: ansible_distribution == "Archlinux"
    - name: Update Packages (rpm)
      command: "yum upgrade -y"
      when: ansible_distribution in ['CentOS', 'Rocky']